const data = [
    {
      id: 1,
      carImg: './../../public/car img/dena-1.png',
      carLogo: './../../public/car logo/Peugeot.png',
      carName: 'دنا',
      carYear: '1401',
      carGirbox: 'دنده ای',
      carColor: 'دلفینی',
      carSokht: 'بنزینی',
      carKarkard: '43,000',
      carBime: '6 ماه',
      carTozih: ' همه مدارک مورد است',
      carPrice: '930,000,000',
      classImg: "",
      BgCar: "bg-orange-300 ring-orange-300",
      bgBtn: "bg-orange-600 ring-orange-600",
    },
    {
      id: 2,
      carImg: './../../public/car img/Lamari-1.png',
      carLogo: './../../public/car logo/logo.png',
      carName: 'لاماری',
      carYear: '1402',
      carGirbox: 'اتومات',
      carColor: 'سفید',
      carSokht: 'بنزینی',
      carKarkard: '0',
      carBime: '12 ماه',
      carTozih: ' همه مدارک موجورد است',
      carPrice: '2,550,000,000',
      classImg: "rotate-3",
      BgCar: "bg-blue-300 ring-blue-300",
      bgBtn: "bg-blue-600 ring-blue-600",

    },
    {
      id: 3,
      carImg: './../../public/car img/dena-1.png',
      carLogo: './../../public/car logo/Peugeot.png',
      carName: 'دنا',
      carYear: '1401',
      carGirbox: 'دنده ای',
      carColor: 'دلفینی',
      carSokht: 'بنزینی',
      carKarkard: '43,000',
      carBime: '6 ماه',
      carTozih: ' همه مدارک مورد است',
      carPrice: '930,000,000',
      classImg: "",
      BgCar: "bg-green-400 ring-green-400",
      bgBtn: "bg-green-600 ring-green-600",

    },
  ];
  export default data