const data = [
    {
      id: 1,
      carImg: 'https://s8.uupload.ir/files/dena-1_pzbm.png',
      carLogo: 'https://s8.uupload.ir/files/asdasdasd_copy_irvf.png',
      carName: 'دنا',
      carYear: '1401',
      carGirbox: 'دنده ای',
      carColor: 'دلفینی',
      carSokht: 'بنزینی',
      carKarkard: '43,000',
      carBime: '6 ماه',
      carTozih: ' همه مدارک موجود است',
      carPrice: '990,000,000',
      classImg: "",
      classLogo: "h-12",
      BgCar: "bg-orange-300 ring-orange-300",
      bgBtn: "bg-orange-600 ring-orange-600",
    },
    {
      id: 2,
      carImg: 'https://s8.uupload.ir/files/lamari-1_6ate.png',
      carLogo: 'https://s8.uupload.ir/files/logo_i2ws.png',
      carName: 'لاماری',
      carYear: '1402',
      carGirbox: 'اتومات',
      carColor: 'سفید',
      carSokht: 'بنزینی',
      carKarkard: '0',
      carBime: '12 ماه',
      carTozih: ' همه مدارک موجود است',
      carPrice: '2,550,000,000',
      classImg: "rotate-3",
      classLogo: "",
      BgCar: "bg-green-300 ring-green-300",
      bgBtn: "bg-green-600 ring-green-600",

    },
    {
      id: 3,
      carImg: 'https://s8.uupload.ir/files/24-798x452-removebg_kz4h.png',
      carLogo: 'https://s8.uupload.ir/files/chery_logo_cgdu.png',
      carName: 'تیگو 8 پرو مکس',
      carYear: '1402',
      carGirbox: 'اتومات',
      carColor: 'مشکی',
      carSokht: 'بنزینی',
      carKarkard: '0',
      carBime: '11 ماه',
      carTozih: ' همه مدارک موجود است',
      carPrice: '3,350,000,000',
      classImg: "",
      classLogo: "",
      BgCar: "bg-blue-300 ring-blue-300",
      bgBtn: "bg-blue-600 ring-blue-600",
    },
  ];
  export default data